### ISSUE TITLE
application registration

### ISSUE THREAD

**Issue by tagorenavabothu** [Medisana/Android-Standalone#2]
Hi,
   i'm working on android application sample(Android-Standalone).after login i'm redirecting to the website url which i had given in the Callback url (url of my website) in the application form. from there it is not comming back to the app. came to know that we have to register an interface more mobile application where should i do that. can u please elaborate the procedure how to do that.

Thanks

**Comment by mgarmuno** [comment]
Hi,
when you change the CALL_BACK_URI in ConstantStorage you need to change this in AndroidManifest too:

<activity
            android:name=".util.CallbackHandler"
            android:label="@string/app_name" >
            <intent-filter>
                <data android:scheme="vdodemo" /> 

```
            <action android:name="android.intent.action.VIEW" />

            <category android:name="android.intent.category.DEFAULT" />
            <category android:name="android.intent.category.BROWSABLE" />
        </intent-filter>
    </activity>
```

Did you change this?

**Comment by tagorenavabothu** [comment]
this is the value in the CALL_BACK_URI.

   public static final String CALL_BACK_URI = "vdodemo" + "://?";

this is there in the android xml file.

   android:scheme="vdodemo"

  android:name="android.intent.action.VIEW" 

   android:name="android.intent.category.DEFAULT" 

   android:name="android.intent.category.BROWSABLE" 

app_name is the "TestApp" which i had given in the application form.

**Comment by mgarmuno** [comment]
I think the problem is in the callback url configuration of your app, you need go to your app configuration in our web and check that.

Please go to https://cloud.vitadock.com/, click on settings/applications, then manage own applications, and show application(binocular icon). Here you can check the Callback URL.
![untitled](https://cloud.githubusercontent.com/assets/10324660/7533964/246f164a-f576-11e4-911e-5868264ad079.png)

 Then you need to replace instead "vdodemo" whit out ://, you need to replace that in ConstantStoreage and AndroidManifest.

**Comment by tagorenavabothu** [comment]
callback url in the ConstantStoreage
 public static final String CALL_BACK_URI = "http://www.healthmultiplex.com" + "://?";

AndroidManifest
android:scheme="http://www.healthmultiplex.com"

this is the callback url in the application.
Callback URL :
http://www.healthmultiplex.com://

is there any way to get the data from the cardio dock blood pressure monitor. i have the verifier token and access token how can i get the data without the callback url.is there any piece of code.

**Comment by ClemensLode** [comment]
You cannot use a http protocol as a callback URL for a mobile application. 
The browser running on android will interpret http as an internet request.
If you use the custom protocol instead (e.g., vdodemo://), android will interpret it as an application call.

An alternative without the callback URL would be a simple popup where the user can enter the verifier token manually.
