### ISSUE TITLE
unable to get targetscales data.

### ISSUE THREAD

**Issue by tagorenavabothu** [Medisana/Android-Standalone#3]
Hi,
     i'm unable to get the data from targetscales. i'm able to pull the data for cardiodocks and oxymeters it. i tried to figure it out found that it is going to "EXCEPTION_ERROR" which results null data. what should i do to pull the data with targetscales.

Thank you.

**Comment by mgarmuno** [comment]
Hi,
can you paste here the exception text of Logcat please?

**Comment by tagorenavabothu** [comment]
Hi,
      i'm not able to connect the device to get the logcat. i think there is something is going on here.

 public void clickedGetSomeData(View v) {
        Intent intent = new Intent(this, GetDataActivity.class);
        intent.putExtra(ConstantsStorage.DATA_MODEL, ConstantsStorage.MODULE_NAMES.indexOf(spinnerModuleName.getSelectedItem().toString()));

intent.putExtra(ConstantsStorage.MODULE_NAME, spinnerModuleName.getSelectedItem().toString());

```
    startActivityForResult(intent, ConstantsStorage.GET_DATA_ACTIVITY_CODE);
```

 }

onActivityResult(int requestCode, int resultCode, Intent data){

...

  Toast.makeText(getApplicationContext(),"intent data : "+data.getStringExtra(ConstantsStorage.MODULE_NAME),Toast.LENGTH_SHORT).show();

.....

}

i tried to toast to check if i'm getting "modulename" or not. for targetscales it is returning "null" and for oxymeters and cardidocks it is returning the corresponding modulenames.

i think there is something going wrong when "targetscales" selected.

**Comment by tagorenavabothu** [comment]
05-12 22:07:56.779  31039-31039/com.example.miguel.myapplication I/SurfaceTextureClient﹕ [0x52939378] frames:2, duration:4.088000, fps:0.489158
05-12 22:07:56.844  31039-31039/com.example.miguel.myapplication D/AbsListView﹕ checkAbsListViewlLogProperty get invalid command
05-12 22:07:56.920  31039-31039/com.example.miguel.myapplication V/InputMethodManager﹕ Not IME target window, ignoring
05-12 22:07:58.070  31039-31039/com.example.miguel.myapplication I/SurfaceTextureClient﹕ [0x52f48bc8] frames:3, duration:1.141000, fps:2.628515
05-12 22:07:59.427  31039-31039/com.example.miguel.myapplication D/VelocityTracker﹕ VelocityTracker: int datax = 10
05-12 22:07:59.428  31039-31039/com.example.miguel.myapplication D/VelocityTracker﹕ VelocityTracker: int m_velocity_magnify_x = 1.000000
05-12 22:07:59.428  31039-31039/com.example.miguel.myapplication D/VelocityTracker﹕ VelocityTracker: int datay = 10
05-12 22:07:59.428  31039-31039/com.example.miguel.myapplication D/VelocityTracker﹕ VelocityTracker: int m_velocity_magnify_y = 1.000000
05-12 22:07:59.583  31039-31039/com.example.miguel.myapplication I/SurfaceTextureClient﹕ [0x52f48bc8] frames:16, duration:1.508000, fps:10.604116
05-12 22:07:59.627  31039-31039/com.example.miguel.myapplication V/Provider/Setting﹕ from settings cache , name = sound_effects_enabled value = 0
05-12 22:07:59.630  31039-31039/com.example.miguel.myapplication D/OpenGLRenderer﹕ Flushing caches (mode 0)
05-12 22:07:59.677  31039-31039/com.example.miguel.myapplication D/AbsListView﹕ resetScrollY: mScrollY = 0,this = android.widget.ListPopupWindow$DropDownListView@416c8070
05-12 22:07:59.689  31039-31039/com.example.miguel.myapplication I/SurfaceTextureClient﹕ [0x52939378] frames:2, duration:2.907000, fps:0.687823
05-12 22:07:59.690  31039-31039/com.example.miguel.myapplication V/InputMethodManager﹕ onWindowFocus: null softInputMode=32 first=false flags=#1810100
05-12 22:08:15.032  31039-31039/com.example.miguel.myapplication I/SurfaceTextureClient﹕ [STC::queueBuffer] this:0x52939378, api:1, last queue time elapsed :15345 ms
05-12 22:08:15.032  31039-31039/com.example.miguel.myapplication I/SurfaceTextureClient﹕ [0x52939378] frames:1, duration:15.345000, fps:0.065167
05-12 22:08:15.114  31039-31039/com.example.miguel.myapplication V/Provider/Setting﹕ from settings cache , name = sound_effects_enabled value = 0
05-12 22:08:15.173  31039-31039/com.example.miguel.myapplication D/ActivityThread﹕ ACT-AM_ON_PAUSE_CALLED ActivityRecord{414ce208 token=android.os.BinderProxy@414cd900 {com.example.miguel.myapplication/com.example.miguel.myapplication.activity.SelectDataTypeActivity}}
05-12 22:08:15.217  31039-31039/com.example.miguel.myapplication D/ActivityThread﹕ ACT-PAUSE_ACTIVITY handled : 1 / android.os.BinderProxy@414cd900
05-12 22:08:15.263  31039-31039/com.example.miguel.myapplication D/dalvikvm﹕ create interp thread : stack size=32KB
05-12 22:08:15.263  31039-31039/com.example.miguel.myapplication D/dalvikvm﹕ create new thread
05-12 22:08:15.264  31039-31039/com.example.miguel.myapplication D/dalvikvm﹕ update thread list
05-12 22:08:15.264  31039-31210/com.example.miguel.myapplication D/dalvikvm﹕ threadid=16: interp stack at 0x52da2000
05-12 22:08:15.264  31039-31210/com.example.miguel.myapplication D/dalvikvm﹕ threadid=16: created from interp
05-12 22:08:15.264  31039-31039/com.example.miguel.myapplication D/dalvikvm﹕ start new thread
05-12 22:08:15.270  31039-31210/com.example.miguel.myapplication D/dalvikvm﹕ threadid=16: notify debugger
05-12 22:08:15.270  31039-31210/com.example.miguel.myapplication D/dalvikvm﹕ threadid=16 (AsyncTask #5): calling run()
05-12 22:08:15.275  31039-31039/com.example.miguel.myapplication D/ActivityThread﹕ ACT-AM_ON_RESUME_CALLED ActivityRecord{416de288 token=android.os.BinderProxy@416dd978 {com.example.miguel.myapplication/com.example.miguel.myapplication.activity.asynctask.GetDataActivity}}
05-12 22:08:15.281  31039-31039/com.example.miguel.myapplication D/ActivityThread﹕ ACT-LAUNCH_ACTIVITY handled : 0 / ActivityRecord{416de288 token=android.os.BinderProxy@416dd978 {com.example.miguel.myapplication/com.example.miguel.myapplication.activity.asynctask.GetDataActivity}}
05-12 22:08:15.361  31039-31210/com.example.miguel.myapplication I/System.out﹕ httpget:https://cloud.vitadock.com/data/targetscales/sync?max=100&date_since=0
05-12 22:08:15.362  31039-31210/com.example.miguel.myapplication I/System.out﹕ https://cloud.vitadock.com/data/targetscales/sync?max=100&date_since=0
05-12 22:08:15.362  31039-31210/com.example.miguel.myapplication I/System.out﹕ Request GET URL:https://cloud.vitadock.com/data/targetscales/sync?max=100&date_since=0
05-12 22:08:15.362  31039-31210/com.example.miguel.myapplication I/System.out﹕ Authorization : OAuth oauth_consumer_key="rhipvgKKl0XMD92bPTwZa1btuRGvm60o4vnf4NMKJZjgFoUmDwJPwRoShX3PKX8y",oauth_signature_method="HMAC-SHA256",oauth_timestamp="1431448695271",oauth_nonce="mjb60DrTYZxak4AynYzyvgR0lLgsQX3LspKd",oauth_token="WkzBxWb9EaihwF5VcE5EgJwYwAWavFm2ybjLqFNgaen6nzdt156daCLZunMaLWzJ",oauth_version="1.0",oauth_signature="Hn%2FubNjPSSRFw01aHRfSNApb82PyHWr6XcSqU3WuHMw%3D"
05-12 22:08:15.497  31039-31041/com.example.miguel.myapplication D/dalvikvm﹕ GC_CONCURRENT freed 1941K, 23% free 7188K/9271K, paused 12ms+4ms, total 120ms
05-12 22:08:15.509  31039-31049/com.example.miguel.myapplication I/System.out﹕ [CDS]close[56793]
05-12 22:08:15.510  31039-31049/com.example.miguel.myapplication I/System.out﹕ close [socket][/0.0.0.0:56793]
05-12 22:08:15.511  31039-31049/com.example.miguel.myapplication I/System.out﹕ close [socket][/0.0.0.0:56793]
05-12 22:08:15.543  31039-31039/com.example.miguel.myapplication D/OpenGLRenderer﹕ Flushing caches (mode 0)
05-12 22:08:15.544  31039-31210/com.example.miguel.myapplication I/System.out﹕ propertyValue:true
05-12 22:08:15.545  31039-31210/com.example.miguel.myapplication I/System.out﹕ [socket][6] connection /192.166.192.66:443;LocalPort=58917(0)
05-12 22:08:15.546  31039-31210/com.example.miguel.myapplication I/System.out﹕ [CDS]connect[/192.166.192.66:443] tm:90
05-12 22:08:15.547  31039-31210/com.example.miguel.myapplication D/Posix﹕ [Posix_connect Debug]Process com.example.miguel.myapplication :443
05-12 22:08:15.729  31039-31210/com.example.miguel.myapplication I/System.out﹕ [socket][/192.168.1.2:58917] connected
05-12 22:08:15.729  31039-31210/com.example.miguel.myapplication I/System.out﹕ [CDS]rx timeout:0
05-12 22:08:15.732  31039-31210/com.example.miguel.myapplication D/NativeCrypto﹕ ssl=0x52b68dc8 NativeCrypto_SSL_do_handshake fd=0x21100005 shc=0x22d00009 timeout_millis=0 client_mode=1 npn=0x0
05-12 22:08:15.732  31039-31210/com.example.miguel.myapplication D/NativeCrypto﹕ doing handshake ++
05-12 22:08:15.732  31039-31210/com.example.miguel.myapplication D/NativeCrypto﹕ ssl=0x52b68dc8 info_callback where=0x10 ret=1
05-12 22:08:15.732  31039-31210/com.example.miguel.myapplication D/NativeCrypto﹕ ssl=0x52b68dc8 handshake start in UNKWN  before/connect initialization
05-12 22:08:15.732  31039-31210/com.example.miguel.myapplication D/NativeCrypto﹕ ssl=0x52b68dc8 info_callback ignored
05-12 22:08:15.732  31039-31210/com.example.miguel.myapplication D/NativeCrypto﹕ ssl=0x52b68dc8 info_callback where=0x1001 ret=1
05-12 22:08:15.732  31039-31210/com.example.miguel.myapplication D/NativeCrypto﹕ ssl=0x52b68dc8 SSL_connect:UNKWN  before/connect initialization
05-12 22:08:15.732  31039-31210/com.example.miguel.myapplication D/NativeCrypto﹕ ssl=0x52b68dc8 info_callback ignored
05-12 22:08:15.732  31039-31210/com.example.miguel.myapplication D/NativeCrypto﹕ ssl=0x52b68dc8 info_callback where=0x1001 ret=1
05-12 22:08:15.732  31039-31210/com.example.miguel.myapplication D/NativeCrypto﹕ ssl=0x52b68dc8 SSL_connect:3WCH_A SSLv3 write client hello A
05-12 22:08:15.732  31039-31210/com.example.miguel.myapplication D/NativeCrypto﹕ ssl=0x52b68dc8 info_callback ignored
05-12 22:08:15.732  31039-31210/com.example.miguel.myapplication D/NativeCrypto﹕ ssl=0x52b68dc8 info_callback where=0x1002 ret=-1
05-12 22:08:15.732  31039-31210/com.example.miguel.myapplication D/NativeCrypto﹕ ssl=0x52b68dc8 SSL_connect:error exit in 3RSH_A SSLv3 read server hello A
05-12 22:08:15.732  31039-31210/com.example.miguel.myapplication D/NativeCrypto﹕ ssl=0x52b68dc8 info_callback ignored
05-12 22:08:15.732  31039-31210/com.example.miguel.myapplication D/NativeCrypto﹕ doing handshake -- ret=-1
05-12 22:08:15.732  31039-31210/com.example.miguel.myapplication D/NativeCrypto﹕ ssl=0x52b68dc8 NativeCrypto_SSL_do_handshake ret=-1 errno=11 sslError=2 timeout_millis=0
05-12 22:08:15.732  31039-31210/com.example.miguel.myapplication D/NativeCrypto﹕ sslSelect type=READ fd=48 appData=0x52ba9f90 timeout_millis=0
05-12 22:08:15.927  31039-31210/com.example.miguel.myapplication D/NativeCrypto﹕ sslSelect READ fd=48 appData=0x52ba9f90 timeout_millis=0 => 1
05-12 22:08:15.927  31039-31210/com.example.miguel.myapplication D/NativeCrypto﹕ doing handshake ++
05-12 22:08:15.927  31039-31210/com.example.miguel.myapplication D/NativeCrypto﹕ ssl=0x52b68dc8 info_callback where=0x1001 ret=1
05-12 22:08:15.927  31039-31210/com.example.miguel.myapplication D/NativeCrypto﹕ ssl=0x52b68dc8 SSL_connect:3RSH_A SSLv3 read server hello A
05-12 22:08:15.927  31039-31210/com.example.miguel.myapplication D/NativeCrypto﹕ ssl=0x52b68dc8 info_callback ignored
05-12 22:08:15.930  31039-31210/com.example.miguel.myapplication D/NativeCrypto﹕ ssl=0x52b68dc8 info_callback where=0x1001 ret=1
05-12 22:08:15.930  31039-31210/com.example.miguel.myapplication D/NativeCrypto﹕ ssl=0x52b68dc8 SSL_connect:3RFINA SSLv3 read finished A
05-12 22:08:15.930  31039-31210/com.example.miguel.myapplication D/NativeCrypto﹕ ssl=0x52b68dc8 info_callback ignored
05-12 22:08:15.930  31039-31210/com.example.miguel.myapplication D/NativeCrypto﹕ ssl=0x52b68dc8 info_callback where=0x1001 ret=1
05-12 22:08:15.930  31039-31210/com.example.miguel.myapplication D/NativeCrypto﹕ ssl=0x52b68dc8 SSL_connect:3WCCSA SSLv3 write change cipher spec A
05-12 22:08:15.930  31039-31210/com.example.miguel.myapplication D/NativeCrypto﹕ ssl=0x52b68dc8 info_callback ignored
05-12 22:08:15.930  31039-31210/com.example.miguel.myapplication D/NativeCrypto﹕ ssl=0x52b68dc8 info_callback where=0x1001 ret=1
05-12 22:08:15.930  31039-31210/com.example.miguel.myapplication D/NativeCrypto﹕ ssl=0x52b68dc8 SSL_connect:3WFINA SSLv3 write finished A
05-12 22:08:15.930  31039-31210/com.example.miguel.myapplication D/NativeCrypto﹕ ssl=0x52b68dc8 info_callback ignored
05-12 22:08:15.930  31039-31210/com.example.miguel.myapplication D/NativeCrypto﹕ ssl=0x52b68dc8 info_callback where=0x1001 ret=1
05-12 22:08:15.930  31039-31210/com.example.miguel.myapplication D/NativeCrypto﹕ ssl=0x52b68dc8 SSL_connect:3FLUSH SSLv3 flush data
05-12 22:08:15.930  31039-31210/com.example.miguel.myapplication D/NativeCrypto﹕ ssl=0x52b68dc8 info_callback ignored
05-12 22:08:15.930  31039-31210/com.example.miguel.myapplication D/NativeCrypto﹕ ssl=0x52b68dc8 info_callback where=0x20 ret=1
05-12 22:08:15.930  31039-31210/com.example.miguel.myapplication D/NativeCrypto﹕ ssl=0x52b68dc8 handshake done in SSLOK  SSL negotiation finished successfully
05-12 22:08:15.930  31039-31210/com.example.miguel.myapplication D/NativeCrypto﹕ ssl=0x52b68dc8 info_callback calling handshakeCompleted
05-12 22:08:15.930  31039-31210/com.example.miguel.myapplication D/NativeCrypto﹕ ssl=0x52b68dc8 info_callback completed
05-12 22:08:15.930  31039-31210/com.example.miguel.myapplication D/NativeCrypto﹕ ssl=0x52b68dc8 info_callback where=0x1002 ret=1
05-12 22:08:15.930  31039-31210/com.example.miguel.myapplication D/NativeCrypto﹕ ssl=0x52b68dc8 SSL_connect:ok exit in SSLOK  SSL negotiation finished successfully
05-12 22:08:15.930  31039-31210/com.example.miguel.myapplication D/NativeCrypto﹕ ssl=0x52b68dc8 info_callback ignored
05-12 22:08:15.930  31039-31210/com.example.miguel.myapplication D/NativeCrypto﹕ doing handshake -- ret=1
05-12 22:08:15.933  31039-31210/com.example.miguel.myapplication I/System.out﹕ >doSendRequest
05-12 22:08:15.937  31039-31210/com.example.miguel.myapplication D/NativeCrypto﹕ ssl=0x52b68dc8 sslWrite buf=0x41503130 len=559
05-12 22:08:15.937  31039-31210/com.example.miguel.myapplication D/NativeCrypto﹕ Doing SSL_write() with 559 bytes to go ssl=0x52b68dc8, appData=0x52ba9f90
05-12 22:08:15.937  31039-31210/com.example.miguel.myapplication D/NativeCrypto﹕ Returned from SSL_write() with result 559, error code 0 ssl=0x52b68dc8, appData=0x52ba9f90
05-12 22:08:15.938  31039-31210/com.example.miguel.myapplication I/System.out﹕ <doSendRequest
05-12 22:08:15.938  31039-31210/com.example.miguel.myapplication D/NativeCrypto﹕ ssl=0x52b68dc8 sslRead buf=0x41506688 len=8192,timeo=0
05-12 22:08:15.938  31039-31210/com.example.miguel.myapplication D/NativeCrypto﹕ Doing SSL_Read() ssl=0x52b68dc8, appData=0x52ba9f90
05-12 22:08:15.938  31039-31210/com.example.miguel.myapplication D/NativeCrypto﹕ Returned from SSL_Read() with result -1, error code 2 ssl=0x52b68dc8, appData=0x52ba9f90
05-12 22:08:15.938  31039-31210/com.example.miguel.myapplication D/NativeCrypto﹕ sslSelect type=READ fd=48 appData=0x52ba9f90 timeout_millis=0
05-12 22:08:16.198  31039-31210/com.example.miguel.myapplication D/NativeCrypto﹕ sslSelect READ fd=48 appData=0x52ba9f90 timeout_millis=0 => 1
05-12 22:08:16.198  31039-31210/com.example.miguel.myapplication D/NativeCrypto﹕ Doing SSL_Read() ssl=0x52b68dc8, appData=0x52ba9f90
05-12 22:08:16.199  31039-31210/com.example.miguel.myapplication D/NativeCrypto﹕ Returned from SSL_Read() with result 170, error code 0 ssl=0x52b68dc8, appData=0x52ba9f90
05-12 22:08:16.201  31039-31210/com.example.miguel.myapplication W/DefaultRequestDirector﹕ Authentication error: Unable to respond to any of these challenges: {}
05-12 22:08:16.204  31039-31039/com.example.miguel.myapplication D/OpenGLRenderer﹕ Flushing caches (mode 0)
05-12 22:08:16.317  31039-31039/com.example.miguel.myapplication D/ActivityThread﹕ ACT-AM_ON_PAUSE_CALLED ActivityRecord{416de288 token=android.os.BinderProxy@416dd978 {com.example.miguel.myapplication/com.example.miguel.myapplication.activity.asynctask.GetDataActivity}}
05-12 22:08:16.338  31039-31039/com.example.miguel.myapplication D/ActivityThread﹕ ACT-PAUSE_ACTIVITY_FINISHING handled : 0 / android.os.BinderProxy@416dd978
05-12 22:08:16.353  31039-31039/com.example.miguel.myapplication D/ActivityThread﹕ SEND_RESULT handled : 0 / ResultData{token=android.os.BinderProxy@414cd900 results[ResultInfo{who=null, request=6, result=2, data=Intent { (has extras) }}]}
05-12 22:08:16.353  31039-31039/com.example.miguel.myapplication D/ActivityThread﹕ ACT-AM_ON_RESUME_CALLED ActivityRecord{414ce208 token=android.os.BinderProxy@414cd900 {com.example.miguel.myapplication/com.example.miguel.myapplication.activity.SelectDataTypeActivity}}
05-12 22:08:16.353  31039-31039/com.example.miguel.myapplication D/ActivityThread﹕ ACT-RESUME_ACTIVITY handled : 0 / android.os.BinderProxy@414cd900
05-12 22:08:16.398  31039-31039/com.example.miguel.myapplication V/InputMethodManager﹕ onWindowFocus: null softInputMode=32 first=true flags=#1810100
05-12 22:08:16.456  31039-31039/com.example.miguel.myapplication D/OpenGLRenderer﹕ Flushing caches (mode 0)
05-12 22:08:16.782  31039-31039/com.example.miguel.myapplication D/OpenGLRenderer﹕ Flushing caches (mode 0)
05-12 22:08:16.785  31039-31039/com.example.miguel.myapplication D/ActivityThread﹕ ACT-DESTROY_ACTIVITY handled : 1 / android.os.BinderProxy@416dd978

**Comment by tagorenavabothu** [comment]
## logcat for cardiodocks. it is fine the server responding with status 200.

05-13 12:40:14.871    4121-4512/com.example.miguel.myapplication D/RetriveData 1﹕ cardiodocks
05-13 12:40:14.926    4121-4512/com.example.miguel.myapplication D/RetriveData 2﹕ https://cloud.vitadock.com/data/cardiodocks/sync?max=100&date_since=0
05-13 12:40:14.942    4121-4512/com.example.miguel.myapplication D/Retrivedata 3﹕ OAuth oauth_consumer_key="YuwVTnmNJYAcCtpY20JtvEwdtJwFFTcMABaMRbhm43pLMCr1dhiwGu5MR3fngfA2",oauth_signature_method="HMAC-SHA256",oauth_timestamp="1431501014927",oauth_nonce="HQVH5YCJJ8gTv4r0rlV0RL0msbpSZM1LpmBJ",oauth_token="n0mxyKEsTEvNbxsM27uUNFzFWfY2SWNh1tNtXhCsKutsgVPLSaVf6iWfAfrFZVEq",oauth_version="1.0",oauth_signature="bAm7yROfEyflBUMlxzaBpRvbemBgrcKbLADxqZA%2Bjt0%3D"
05-13 12:40:15.987    4121-4512/com.example.miguel.myapplication D/RetriveData 4:﹕ org.apache.http.message.BasicHttpResponse@41c67070
05-13 12:40:15.987    4121-4512/com.example.miguel.myapplication D/RetriveData 5:﹕ 200OK

---

## This is the logcat for targetscales. returning a stutus code 401: unauthorized.

05-13 12:39:14.258    4121-4496/com.example.miguel.myapplication D/RetriveData 1﹕ targetscales
05-13 12:39:14.264    4121-4496/com.example.miguel.myapplication D/RetriveData 2﹕ https://cloud.vitadock.com/data/targetscales/sync?max=100&date_since=0
05-13 12:39:14.466    4121-4496/com.example.miguel.myapplication D/Retrivedata 3﹕ OAuth oauth_consumer_key="YuwVTnmNJYAcCtpY20JtvEwdtJwFFTcMABaMRbhm43pLMCr1dhiwGu5MR3fngfA2",oauth_signature_method="HMAC-SHA256",oauth_timestamp="1431500954285",oauth_nonce="3PEwMKyfhL9MsCT5dTlWT3judO4N5mS2mxHo",oauth_token="n0mxyKEsTEvNbxsM27uUNFzFWfY2SWNh1tNtXhCsKutsgVPLSaVf6iWfAfrFZVEq",oauth_version="1.0",oauth_signature="Dw3nZ4xnCRjkDHpUDLJhLMmEB3Nq7eTElD3sCSme09Y%3D"
05-13 12:39:15.642    4121-4496/com.example.miguel.myapplication D/RetriveData 4:﹕ org.apache.http.message.BasicHttpResponse@41d9e828

## 05-13 12:39:15.643    4121-4496/com.example.miguel.myapplication D/RetriveData 5:﹕ 401Unauthorized.

**Comment by mgarmuno** [comment]
401 Unauthorized response is caused because you application is not authorized to get this module. Please send a mail to cloud@vitadock.com requesting the targetscales permissions for you application.

**Comment by tagorenavabothu** [comment]
okay got it. :-)

thank you
